language: rust
sudo: false
cache: cargo

matrix:
  allow_failures:
    - rust: nightly
    - os: windows
  fast_finish: true

  include:
    - rust: stable

    - name: "Clippy"
      rust: nightly
      before_script: rustup component add clippy-preview
      script: cargo clippy

    - name: "rustfmt"
      rust: stable
      before_script: rustup component add rustfmt-preview
      script: cargo fmt -- --check

    - name: "warnings"
      rust: stable
      script: cargo check --examples

    - name: "release"
      rust: stable
      script:
        - cargo build --verbose --examples --release
        - cargo test --verbose --release
        - cargo doc --verbose --release

    - os: osx
      osx_image: xcode10
    - os: windows

script:
- cargo build --examples --verbose
- cargo test --verbose
- cargo test --no-default-features
- cargo test --no-default-features --features=lz4
- cargo doc --verbose